// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { digitalchatBlock } from '.'

export const digitalchatBlockSchema = parseBlockSchema(digitalchatBlock)
export const digitalchatCredentialsSchema =
  parseBlockCredentials(digitalchatBlock)
