// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { digitalchatBlock } from './index'
import { auth } from './auth'

export const digitalchatBlockSchema = parseBlockSchema(digitalchatBlock)
export const digitalchatCredentialsSchema = parseBlockCredentials(
  digitalchatBlock.id,
  auth.schema
)
